import type { CSSProperties } from 'react';

const panelShadow = '0 1px 4px rgba(0, 0, 0, 0.08)';

const styles: Record<string, CSSProperties> = {
  page: { maxWidth: 900, margin: '0 auto', padding: '24px 16px' },
  center: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: 200, color: '#64748b' },
  errorBox: { background: '#fef2f2', color: '#b91c1c', padding: '12px 16px', borderRadius: 8, margin: '24px 0' },
  successBox: { background: '#f0fdf4', color: '#166534', padding: '12px 16px', borderRadius: 8, margin: '24px 0' },
  emptyBox: { textAlign: 'center', padding: '48px 0', color: '#64748b' },

  heading: { fontSize: 22, fontWeight: 700, margin: '0 0 4px' },
  subtext: { color: '#64748b', fontSize: 14, margin: '0 0 24px' },
  sectionTitle: { fontSize: 15, fontWeight: 600, margin: '0 0 12px', color: '#334155' },
  badge: {
    background: '#e0e7ff',
    color: '#4338ca',
    borderRadius: 9999,
    padding: '2px 10px',
    fontSize: 13,
    fontWeight: 600,
    marginLeft: 8,
  },
  formLabel: { display: 'block', fontSize: 12, color: '#475569', marginBottom: 8, fontWeight: 600 },
  formHint: { margin: '0 0 14px', color: '#475569', fontSize: 13, lineHeight: 1.5 },
  inlineCode: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    background: '#e2e8f0',
    color: '#0f172a',
    borderRadius: 6,
    padding: '2px 6px',
  },
  formInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 8,
    border: '1px solid #cbd5e1',
    fontSize: 14,
    marginBottom: 14,
    boxSizing: 'border-box',
  },
  buttonRow: { display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 12 },
  primaryButton: {
    background: '#2563eb',
    color: '#fff',
    border: 0,
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  secondaryButton: {
    background: '#fff',
    color: '#334155',
    border: '1px solid #cbd5e1',
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  warningText: { color: '#b45309', fontSize: 13, margin: '0 0 12px', lineHeight: 1.5 },

  kpiRow: { display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 24 },
  kpiCard: {
    flex: '1 1 120px',
    background: '#fff',
    borderRadius: 10,
    padding: '16px',
    boxShadow: panelShadow,
    textAlign: 'center',
  },
  kpiValue: { fontSize: 26, fontWeight: 700, color: '#6366f1' },
  kpiLabel: { fontSize: 12, color: '#64748b', marginTop: 4 },

  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 12 },
  card: {
    background: '#fff',
    borderRadius: 10,
    padding: '16px 12px',
    boxShadow: panelShadow,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  cardSurface: { fontSize: 22, fontWeight: 700, color: '#1e293b', textAlign: 'center' },
  cardReading: { fontSize: 13, color: '#6366f1', textAlign: 'center' },
  cardMeaning: { fontSize: 13, color: '#374151', textAlign: 'center', flexGrow: 1 },
  cardTag: {
    fontSize: 11,
    background: '#f1f5f9',
    color: '#64748b',
    borderRadius: 4,
    padding: '2px 6px',
    alignSelf: 'center',
    marginTop: 4,
  },
  metaRow: { display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'center', marginTop: 4 },
  metaTag: { fontSize: 10, background: '#ecfccb', color: '#3f6212', borderRadius: 9999, padding: '2px 8px' },

  chartBox: { background: '#fff', borderRadius: 10, padding: '20px', boxShadow: panelShadow, marginBottom: 20 },
  insightBox: { background: '#f0fdf4', borderRadius: 10, padding: '16px 20px', marginBottom: 20 },
  insightList: { margin: 0, paddingLeft: 20 },
  insightItem: { marginBottom: 6, fontSize: 14, color: '#166534', lineHeight: 1.6 },
  confusionBox: { background: '#fff', borderRadius: 10, padding: '20px', boxShadow: panelShadow, marginBottom: 20 },
  adminPanel: { background: '#fff', borderRadius: 10, padding: '20px', boxShadow: panelShadow, marginBottom: 20 },
  statusGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, marginBottom: 14 },
  statusCard: { background: '#f8fafc', borderRadius: 8, padding: '14px 12px', display: 'grid', gap: 6 },
  statusLabel: { fontSize: 12, color: '#64748b' },
  statusValue: { fontSize: 15, fontWeight: 600, color: '#0f172a', wordBreak: 'break-word' },
  metricGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12, marginTop: 8 },
  metricCard: { background: '#f8fafc', borderRadius: 8, padding: '14px 12px', textAlign: 'center' },
  metricValue: { fontSize: 24, fontWeight: 700, color: '#1e293b' },
  metricLabel: { fontSize: 12, color: '#64748b', marginTop: 6 },
  resultBox: { background: '#f8fafc', borderRadius: 8, padding: '14px 16px', marginTop: 8, display: 'grid', gap: 10 },
  resultRow: { display: 'flex', justifyContent: 'space-between', gap: 16, fontSize: 14, color: '#1e293b' },
  activityList: { display: 'grid', gap: 10 },
  activityItem: { border: '1px solid #e2e8f0', borderRadius: 8, padding: '12px 14px', background: '#f8fafc' },
  activityMeta: { display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center', marginBottom: 6, color: '#64748b', fontSize: 12 },
  activityAction: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontWeight: 600,
    color: '#0f172a',
  },
  activityStatus: { fontSize: 12, fontWeight: 700, textTransform: 'uppercase' },
  activityMessage: { color: '#334155', fontSize: 14, lineHeight: 1.5 },

  table: { width: '100%', borderCollapse: 'collapse' },
  th: { textAlign: 'left', padding: '8px 12px', fontSize: 13, color: '#64748b', borderBottom: '2px solid #e2e8f0' },
  td: { padding: '8px 12px', fontSize: 14, color: '#1e293b' },
  trEven: { background: '#fff' },
  trOdd: { background: '#f8fafc' },
};

export default styles;
