import type { CSSProperties } from 'react';

const styles: Record<string, CSSProperties> = {
  page: { maxWidth: 960, margin: '0 auto', padding: '24px 16px' },
  center: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 240, color: 'var(--app-text-muted)' },
  errorBox: { background: 'var(--app-error-bg)', color: 'var(--app-error-text)', padding: '12px 16px', borderRadius: 12, margin: '24px 0' },
  successBox: { background: 'var(--app-success-bg)', color: 'var(--app-success-text)', padding: '12px 16px', borderRadius: 12, margin: '24px 0' },
  emptyBox: { textAlign: 'center', padding: '48px 0', color: 'var(--app-text-muted)' },

  heading: { fontSize: 24, fontWeight: 800, margin: '0 0 8px', color: 'var(--app-text)' },
  subtext: { color: 'var(--app-text-muted)', fontSize: 14, margin: '0 0 24px', lineHeight: 1.6 },
  sectionTitle: { fontSize: 15, fontWeight: 700, margin: '0 0 12px', color: 'var(--app-text)' },
  badge: {
    background: 'var(--app-primary-soft)',
    color: 'var(--app-primary)',
    borderRadius: 9999,
    padding: '2px 10px',
    fontSize: 13,
    fontWeight: 700,
    marginLeft: 8,
    border: '1px solid var(--app-primary)',
  },
  formLabel: { display: 'block', fontSize: 12, color: 'var(--app-text-muted)', marginBottom: 8, fontWeight: 700 },
  formHint: { margin: '0 0 14px', color: 'var(--app-text-muted)', fontSize: 13, lineHeight: 1.5 },
  inlineCode: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    background: 'var(--app-surface-alt)',
    color: 'var(--app-text)',
    borderRadius: 6,
    padding: '2px 6px',
  },
  formInput: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid var(--app-border)',
    background: 'var(--app-surface)',
    color: 'var(--app-text)',
    fontSize: 14,
    marginBottom: 14,
    boxSizing: 'border-box',
  },
  buttonRow: { display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 12 },
  primaryButton: {
    background: 'var(--app-primary)',
    color: 'var(--app-primary-contrast)',
    border: 0,
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  },
  secondaryButton: {
    background: 'var(--app-primary-soft)',
    color: 'var(--app-primary)',
    border: '1px solid var(--app-primary)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
  },
  warningText: { color: 'var(--app-text-muted)', fontSize: 13, margin: '0 0 12px', lineHeight: 1.5 },

  kpiRow: { display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 24 },
  kpiCard: {
    flex: '1 1 120px',
    background: 'var(--app-surface)',
    borderRadius: 14,
    padding: '16px',
    boxShadow: 'var(--app-shadow)',
    border: '1px solid var(--app-border)',
    textAlign: 'center',
  },
  kpiValue: { fontSize: 26, fontWeight: 800, color: 'var(--app-primary)' },
  kpiLabel: { fontSize: 12, color: 'var(--app-text-muted)', marginTop: 4 },

  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12 },
  card: {
    background: 'var(--app-surface)',
    borderRadius: 14,
    padding: '16px 12px',
    boxShadow: 'var(--app-shadow)',
    border: '1px solid var(--app-border)',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  cardSurface: { fontSize: 22, fontWeight: 800, color: 'var(--app-text)', textAlign: 'center' },
  cardReading: { fontSize: 13, color: 'var(--app-primary)', textAlign: 'center' },
  cardMeaning: { fontSize: 13, color: 'var(--app-text-muted)', textAlign: 'center', flexGrow: 1 },
  cardTag: {
    fontSize: 11,
    background: 'var(--app-surface-alt)',
    color: 'var(--app-text-muted)',
    borderRadius: 999,
    padding: '2px 8px',
    alignSelf: 'center',
    marginTop: 4,
    border: '1px solid var(--app-border)',
  },
  metaRow: { display: 'flex', gap: 6, flexWrap: 'wrap', justifyContent: 'center', marginTop: 4 },
  metaTag: { fontSize: 10, background: 'var(--app-primary-soft)', color: 'var(--app-primary)', borderRadius: 9999, padding: '2px 8px' },

  chartBox: { background: 'var(--app-surface)', borderRadius: 14, padding: '20px', boxShadow: 'var(--app-shadow)', border: '1px solid var(--app-border)', marginBottom: 20 },
  insightBox: { background: 'var(--app-surface-alt)', borderRadius: 14, padding: '16px 20px', border: '1px solid var(--app-border)', marginBottom: 20 },
  insightList: { margin: 0, paddingLeft: 20 },
  insightItem: { marginBottom: 6, fontSize: 14, color: 'var(--app-text)', lineHeight: 1.6 },
  confusionBox: { background: 'var(--app-surface)', borderRadius: 14, padding: '20px', boxShadow: 'var(--app-shadow)', border: '1px solid var(--app-border)', marginBottom: 20 },
  adminPanel: { background: 'var(--app-surface)', borderRadius: 14, padding: '20px', boxShadow: 'var(--app-shadow)', border: '1px solid var(--app-border)', marginBottom: 20 },
  statusGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, marginBottom: 14 },
  statusCard: { background: 'var(--app-surface-alt)', borderRadius: 10, padding: '14px 12px', display: 'grid', gap: 6, border: '1px solid var(--app-border)' },
  statusLabel: { fontSize: 12, color: 'var(--app-text-muted)' },
  statusValue: { fontSize: 15, fontWeight: 700, color: 'var(--app-text)', wordBreak: 'break-word' },
  metricGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12, marginTop: 8 },
  metricCard: { background: 'var(--app-surface-alt)', borderRadius: 10, padding: '14px 12px', textAlign: 'center', border: '1px solid var(--app-border)' },
  metricValue: { fontSize: 24, fontWeight: 800, color: 'var(--app-text)' },
  metricLabel: { fontSize: 12, color: 'var(--app-text-muted)', marginTop: 6 },
  resultBox: { background: 'var(--app-surface-alt)', borderRadius: 10, padding: '14px 16px', marginTop: 8, display: 'grid', gap: 10, border: '1px solid var(--app-border)' },
  resultRow: { display: 'flex', justifyContent: 'space-between', gap: 16, fontSize: 14, color: 'var(--app-text)' },
  activityList: { display: 'grid', gap: 10 },
  activityItem: { border: '1px solid var(--app-border)', borderRadius: 10, padding: '12px 14px', background: 'var(--app-surface-alt)' },
  activityMeta: { display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center', marginBottom: 6, color: 'var(--app-text-muted)', fontSize: 12 },
  activityAction: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontWeight: 700,
    color: 'var(--app-text)',
  },
  activityStatus: { fontSize: 12, fontWeight: 700, textTransform: 'uppercase' },
  activityMessage: { color: 'var(--app-text)', fontSize: 14, lineHeight: 1.5 },

  table: { width: '100%', borderCollapse: 'collapse' },
  th: { textAlign: 'left', padding: '8px 12px', fontSize: 13, color: 'var(--app-text-muted)', borderBottom: '2px solid var(--app-border)' },
  td: { padding: '8px 12px', fontSize: 14, color: 'var(--app-text)' },
  trEven: { background: 'var(--app-surface)' },
  trOdd: { background: 'var(--app-surface-alt)' },
};

export default styles;
