import type { SupportedLocale, ThemePreference } from './types/api-contracts';

export const UI_LOCALES: SupportedLocale[] = ['ko', 'en', 'ja'];
export const THEME_OPTIONS: ThemePreference[] = ['system', 'light', 'dark'];

export const LOCALE_LABELS: Record<SupportedLocale, string> = {
  ko: '한국어',
  en: 'English',
  ja: '日本語',
};

const EN = {
  'app.name': 'Japanese Learn',
  'common.loading': 'Loading...',
  'common.retry': 'Retry',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.confirm': 'Confirm',
  'common.export': 'Export data',
  'common.logout': 'Log out',
  'tab.home': 'Home',
  'tab.session': 'Study',
  'tab.plan': 'Plan',
  'tab.report': 'Report',
  'tab.settings': 'Settings',
  'theme.system': 'System',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'settings.title': 'Settings',
  'settings.appearance': 'Appearance',
  'settings.language': 'Language',
  'settings.privacy': 'Privacy',
  'settings.account': 'Account',
  'settings.themeSaved': 'Theme was synced across devices.',
  'settings.languageSaved': 'Language was synced across devices.',
  'settings.deleteTitle': 'Delete account and all data',
  'settings.deleteDescription':
    'Deleting your account permanently removes study history, diagnosis results, experiments, and notification settings.',
  'settings.deleteConfirmLabel': 'Deletion confirmation phrase',
  'settings.deleteConfirmHint': 'Type the exact phrase below before deletion is allowed.',
  'settings.deletePhrase': 'DELETE MY ACCOUNT',
  'settings.deleteAck': 'I understand export is available and deletion is permanent.',
  'settings.deleteCta': 'Delete account and all data',
  'settings.deleteSuccess': 'Your account and all data were deleted.',
  'settings.deleteFailure': 'Failed to delete your account.',
  'settings.exportHint': 'You can export your data as JSON before deleting it.',
  'settings.localeLabel': 'Current language',
  'settings.themeLabel': 'Current theme',
  'settings.requiredConsent': 'Required consent',
  'settings.researchOptIn': 'Research opt-in',
  'settings.diagnosisVersion': 'Diagnosis version',
  'settings.rawRetention': 'Raw event retention',
  'settings.aggRetention': 'Aggregate retention',
  'settings.exportSupport': 'Export supported',
  'settings.deleteSupport': 'Immediate delete supported',
  'settings.notificationOptIn': 'Notifications allowed',
  'settings.targetLevel': 'Target level',
  'settings.targetDate': 'Target date',
  'settings.dailyMinutes': 'Daily study time',
  'settings.weeklyVariability': 'Weekly variability',
  'settings.offlineExpected': 'Offline expected',
  'settings.kanjiBackground': 'Kanji background',
  'settings.unset': 'Unset',
  'settings.minutes': '{count} min',
  'settings.days': '{count} days',
  'login.title': 'Japanese learning app',
  'login.subtitle': 'Build durable memory with spaced repetition and retrieval practice.',
  'login.google': 'Continue with Google',
  'login.security':
    'Sign in securely with Google OAuth. Passwords and sensitive account data are not stored in this app.',
  'login.dev': 'Open web dev mode',
  'login.failed': 'Login failed',
  'consent.title': 'Privacy and consent',
  'consent.subtitle': 'Review the consent choices required to use the service.',
  'consent.requiredTitle': 'Required consent',
  'consent.optionalTitle': 'Optional consent',
  'consent.researchTitle': 'Research participation',
  'consent.requiredDesc':
    'Only the minimum data needed for study history and personalization is used.',
  'consent.optionalDesc': 'Extra analytics for product improvement. Off by default.',
  'consent.researchDesc': 'Allow anonymous research statistics. Off by default.',
  'consent.submit': 'Accept and continue',
  'consent.requiredNeeded': 'Required consent is needed.',
  'home.title': 'Today',
  'home.subtitle': 'Use spaced repetition and retrieval practice to build long-term memory.',
  'home.todayQueue': 'Cards for today',
  'home.reviewCount': 'Review {count}',
  'home.newCount': 'New {count}',
  'home.startSession': 'Start study',
  'home.allClear': 'You cleared today\'s queue.',
  'home.features': 'Features',
  'home.feature.srsTitle': 'Spaced repetition',
  'home.feature.srsDesc': 'Check today\'s review and new card counts.',
  'home.feature.retrievalTitle': 'Retrieval practice',
  'home.feature.retrievalDesc': 'Recall the answer before seeing it.',
  'home.feature.planTitle': 'Personalized plan',
  'home.feature.planDesc': 'Adjust the plan using diagnosis and behavior data.',
  'home.feature.offlineTitle': 'Offline queue',
  'home.feature.offlineDesc': '{count} events waiting to sync',
  'home.rediagnose': 'Run diagnosis again',
  'home.refresh': 'Refresh',
  'plan.title': 'Today plan',
  'plan.subtitle': 'Blend diagnosis and recent behavior to shape today\'s study strategy.',
  'plan.missingTitle': 'Diagnosis result not found',
  'plan.missingDesc': 'Complete diagnosis first to unlock a personalized plan.',
  'plan.restartDiagnosis': 'Restart diagnosis',
  'plan.strategyVector': 'Strategy vector',
  'plan.notes': 'Diagnosis notes',
  'plan.summary': 'Plan summary',
  'plan.explanation': 'Explanation receipt',
  'plan.recovery': 'Recovery plan',
  'plan.evidence': 'Evidence',
  'plan.confidence': 'Confidence by axis',
  'plan.counterfactual': 'Counterfactual',
  'report.title': 'Weekly report',
  'report.loading': 'Generating report...',
  'report.empty': 'There is not enough study data yet to build a report.',
  'report.analysis': 'This week',
  'report.delayedRecall': '7d delayed recall',
  'report.totalReviews': 'Total reviews',
  'report.newCards': 'New cards',
  'report.accuracy': 'Average accuracy',
  'report.streak': 'Streak',
  'report.confusions': 'Top confusions',
  'report.recovery': 'Recovery metrics',
  'web.loginTitle': 'Japanese Learn Web',
  'web.loginSubtitle':
    'Sign in with Google to review your queue, report, experiments, and settings.',
  'web.nav.today': 'Today',
  'web.nav.report': 'Report',
  'web.nav.experiments': 'Experiments',
  'web.nav.settings': 'Settings',
  'web.today.title': 'Today queue',
  'web.today.empty': 'All cards are clear for today.',
  'web.today.drills': 'Drills',
  'web.today.plan': 'Plan explanation',
  'web.report.title': 'Weekly report',
  'web.experiments.title': 'Experiment assignments',
  'web.experiments.subtitle':
    'See which experiment is active for this user and why it exists.',
  'web.settings.title': 'Settings',
  'web.settings.subtitle':
    'Manage the theme and language shared across mobile and web.',
  'web.delete.redirect': 'After deletion, you will be redirected to the login page.',
} as const;

type UiCopyKey = keyof typeof EN;
type UiCopyTable = Record<UiCopyKey, string>;

const KO: UiCopyTable = {
  ...EN,
  'common.loading': '불러오는 중...',
  'common.retry': '다시 시도',
  'common.save': '저장',
  'common.cancel': '취소',
  'common.delete': '삭제',
  'common.confirm': '확인',
  'common.export': '데이터 내보내기',
  'common.logout': '로그아웃',
  'tab.home': '홈',
  'tab.session': '학습',
  'tab.plan': '플랜',
  'tab.report': '리포트',
  'tab.settings': '설정',
  'theme.system': '시스템',
  'theme.light': '라이트',
  'theme.dark': '다크',
  'settings.title': '설정',
  'settings.appearance': '화면 모드',
  'settings.language': '언어',
  'settings.privacy': '프라이버시',
  'settings.account': '계정',
  'settings.themeSaved': '화면 모드가 모든 기기에 동기화되었습니다.',
  'settings.languageSaved': '언어 설정이 모든 기기에 동기화되었습니다.',
  'settings.deleteTitle': '계정 및 모든 데이터 삭제',
  'settings.deleteDescription':
    '계정을 삭제하면 학습 기록, 진단 결과, 실험 배정, 알림 설정이 영구적으로 삭제됩니다.',
  'settings.deleteConfirmLabel': '삭제 확인 문구',
  'settings.deleteConfirmHint': '아래 문구를 정확히 입력해야 삭제를 진행할 수 있습니다.',
  'settings.deleteAck': '내보내기 가능 여부를 확인했고, 삭제가 영구적임을 이해했습니다.',
  'settings.deleteCta': '계정 및 모든 데이터 삭제',
  'settings.deleteSuccess': '계정과 모든 데이터가 삭제되었습니다.',
  'settings.deleteFailure': '계정 삭제에 실패했습니다.',
  'settings.exportHint': '삭제 전에 데이터를 JSON으로 내보낼 수 있습니다.',
  'settings.localeLabel': '현재 언어',
  'settings.themeLabel': '현재 화면 모드',
  'settings.requiredConsent': '필수 동의',
  'settings.researchOptIn': '연구 참여',
  'settings.diagnosisVersion': '진단 버전',
  'settings.rawRetention': '원시 이벤트 보관',
  'settings.aggRetention': '집계 데이터 보관',
  'settings.exportSupport': '내보내기 지원',
  'settings.deleteSupport': '즉시 삭제 지원',
  'settings.notificationOptIn': '알림 허용',
  'settings.targetLevel': '목표 레벨',
  'settings.targetDate': '목표 날짜',
  'settings.dailyMinutes': '일일 학습 시간',
  'settings.weeklyVariability': '주간 변동성',
  'settings.offlineExpected': '오프라인 예상',
  'settings.kanjiBackground': '한자 배경',
  'settings.unset': '미설정',
  'settings.minutes': '{count}분',
  'settings.days': '{count}일',
  'login.title': '일본어 학습 앱',
  'login.subtitle': '간격 반복과 인출 연습으로 오래 남는 기억을 만듭니다.',
  'login.google': 'Google로 로그인',
  'login.security':
    'Google OAuth로 안전하게 로그인합니다. 비밀번호와 민감한 계정 정보는 저장하지 않습니다.',
  'login.dev': '웹 개발 모드로 바로 접속',
  'login.failed': '로그인 실패',
  'consent.title': '개인정보 및 동의 설정',
  'consent.subtitle': '서비스 이용에 필요한 동의 항목을 확인해 주세요.',
  'consent.requiredTitle': '필수 동의',
  'consent.optionalTitle': '선택 동의',
  'consent.researchTitle': '연구 참여',
  'consent.requiredDesc': '학습 기록 저장과 개인화된 플랜 계산에 필요한 최소한의 데이터만 사용합니다.',
  'consent.optionalDesc': '기능 개선을 위한 추가 분석 데이터입니다. 기본값은 꺼짐입니다.',
  'consent.researchDesc': '익명화된 연구 통계 사용에 동의합니다. 기본값은 꺼짐입니다.',
  'consent.submit': '동의하고 시작하기',
  'consent.requiredNeeded': '필수 동의가 필요합니다.',
  'home.title': '오늘 학습',
  'home.subtitle': '간격 반복과 인출 연습으로 장기 기억을 만듭니다.',
  'home.todayQueue': '오늘의 카드',
  'home.reviewCount': '복습 {count}',
  'home.newCount': '신규 {count}',
  'home.startSession': '학습 시작',
  'home.allClear': '오늘의 큐를 모두 비웠습니다.',
  'home.features': '기능',
  'home.feature.srsTitle': '간격 반복',
  'home.feature.srsDesc': '오늘의 복습 수와 신규 카드 수를 확인합니다.',
  'home.feature.retrievalTitle': '인출 연습',
  'home.feature.retrievalDesc': '정답을 보기 전에 먼저 떠올립니다.',
  'home.feature.planTitle': '개인화 플랜',
  'home.feature.planDesc': '진단 결과와 행동 데이터를 바탕으로 플랜을 조정합니다.',
  'home.feature.offlineTitle': '오프라인 큐',
  'home.feature.offlineDesc': '동기화 대기 {count}건',
  'home.rediagnose': '진단 다시 받기',
  'home.refresh': '새로고침',
  'plan.title': '오늘 플랜',
  'plan.subtitle': '진단 결과와 최근 행동 데이터를 바탕으로 오늘의 학습 전략을 만듭니다.',
  'plan.missingTitle': '진단 결과가 없습니다',
  'plan.missingDesc': '개인화 플랜을 보려면 먼저 진단을 완료해 주세요.',
  'plan.restartDiagnosis': '진단 다시 시작',
  'plan.strategyVector': '전략 벡터',
  'plan.notes': '진단 노트',
  'plan.summary': '플랜 요약',
  'plan.explanation': '설명 영수증',
  'plan.recovery': '회복 플랜',
  'plan.evidence': '근거',
  'plan.confidence': '축별 신뢰도',
  'plan.counterfactual': '반사실 비교',
  'report.title': '주간 리포트',
  'report.loading': '리포트를 생성하는 중...',
  'report.empty': '리포트를 만들 만큼의 학습 데이터가 아직 없습니다.',
  'report.analysis': '이번 주 분석',
  'report.delayedRecall': '7일 지연 인출',
  'report.totalReviews': '총 복습',
  'report.newCards': '신규 카드',
  'report.accuracy': '평균 정확도',
  'report.streak': '연속 학습',
  'report.confusions': '자주 헷갈리는 항목',
  'report.recovery': '회복 지표',
  'web.loginSubtitle': 'Google로 로그인해 오늘의 큐, 리포트, 실험, 설정을 확인하세요.',
  'web.nav.today': '오늘',
  'web.nav.report': '리포트',
  'web.nav.experiments': '실험',
  'web.nav.settings': '설정',
  'web.today.title': '오늘의 큐',
  'web.today.empty': '오늘 처리할 카드가 없습니다.',
  'web.today.drills': '드릴',
  'web.today.plan': '플랜 설명',
  'web.report.title': '주간 리포트',
  'web.experiments.title': '실험 배정',
  'web.experiments.subtitle': '현재 어떤 실험이 적용 중인지와 목적을 보여줍니다.',
  'web.settings.title': '설정',
  'web.settings.subtitle': '모바일과 웹에 공통으로 적용되는 화면 모드와 언어를 관리합니다.',
  'web.delete.redirect': '삭제 후 로그인 화면으로 이동합니다.',
};

const JA: UiCopyTable = {
  ...EN,
  'common.loading': '読み込み中...',
  'common.retry': '再試行',
  'common.save': '保存',
  'common.cancel': 'キャンセル',
  'common.delete': '削除',
  'common.confirm': '確認',
  'common.export': 'データを書き出す',
  'common.logout': 'ログアウト',
  'tab.home': 'ホーム',
  'tab.session': '学習',
  'tab.plan': 'プラン',
  'tab.report': 'レポート',
  'tab.settings': '設定',
  'theme.system': 'システム',
  'theme.light': 'ライト',
  'theme.dark': 'ダーク',
  'settings.title': '設定',
  'settings.appearance': '表示モード',
  'settings.language': '言語',
  'settings.privacy': 'プライバシー',
  'settings.account': 'アカウント',
  'settings.themeSaved': '表示モードがすべての端末に同期されました。',
  'settings.languageSaved': '言語設定がすべての端末に同期されました。',
  'settings.deleteTitle': 'アカウントとすべてのデータを削除',
  'settings.deleteDescription':
    '削除すると、学習履歴、診断結果、実験割り当て、通知設定が完全に消去されます。',
  'settings.deleteConfirmLabel': '削除確認フレーズ',
  'settings.deleteConfirmHint': '削除するには、下のフレーズを正確に入力してください。',
  'settings.deleteAck': 'エクスポート可能であり、削除が永久的であることを理解しました。',
  'settings.deleteCta': 'アカウントとすべてのデータを削除',
  'settings.deleteSuccess': 'アカウントとすべてのデータを削除しました。',
  'settings.deleteFailure': 'アカウントの削除に失敗しました。',
  'settings.exportHint': '削除前にデータを JSON として書き出せます。',
  'settings.localeLabel': '現在の言語',
  'settings.themeLabel': '現在の表示モード',
  'settings.requiredConsent': '必須同意',
  'settings.researchOptIn': '研究参加',
  'settings.diagnosisVersion': '診断バージョン',
  'settings.rawRetention': '生イベント保持',
  'settings.aggRetention': '集計データ保持',
  'settings.exportSupport': '書き出し対応',
  'settings.deleteSupport': '即時削除対応',
  'settings.notificationOptIn': '通知許可',
  'settings.targetLevel': '目標レベル',
  'settings.targetDate': '目標日',
  'settings.dailyMinutes': '1日の学習時間',
  'settings.weeklyVariability': '週間変動',
  'settings.offlineExpected': 'オフライン想定',
  'settings.kanjiBackground': '漢字背景',
  'settings.unset': '未設定',
  'settings.minutes': '{count}分',
  'settings.days': '{count}日',
  'login.title': '日本語学習アプリ',
  'login.subtitle': '間隔反復と想起練習で長く残る記憶を作ります。',
  'login.google': 'Google でログイン',
  'login.security':
    'Google OAuth で安全にログインします。パスワードや機密性の高い情報は保存しません。',
  'login.dev': 'Web 開発モードで入る',
  'login.failed': 'ログインに失敗しました',
  'consent.title': 'プライバシーと同意設定',
  'consent.subtitle': 'サービス利用に必要な同意項目を確認してください。',
  'consent.requiredTitle': '必須同意',
  'consent.optionalTitle': '任意同意',
  'consent.researchTitle': '研究参加',
  'consent.requiredDesc': '学習履歴と個別プラン計算に必要な最小限のデータのみ使用します。',
  'consent.optionalDesc': '機能改善のための追加分析です。初期値はオフです。',
  'consent.researchDesc': '匿名化された研究統計への利用に同意します。初期値はオフです。',
  'consent.submit': '同意して開始',
  'consent.requiredNeeded': '必須同意が必要です。',
  'home.title': '今日の学習',
  'home.subtitle': '間隔反復と想起練習で長期記憶を作ります。',
  'home.todayQueue': '今日のカード',
  'home.reviewCount': '復習 {count}',
  'home.newCount': '新規 {count}',
  'home.startSession': '学習開始',
  'home.allClear': '今日のキューはすべて完了しました。',
  'home.features': '機能',
  'home.feature.srsTitle': '間隔反復',
  'home.feature.srsDesc': '今日の復習数と新規カード数を確認します。',
  'home.feature.retrievalTitle': '想起練習',
  'home.feature.retrievalDesc': '答えを見る前に自分で思い出します。',
  'home.feature.planTitle': '個別プラン',
  'home.feature.planDesc': '診断結果と行動データをもとにプランを調整します。',
  'home.feature.offlineTitle': 'オフラインキュー',
  'home.feature.offlineDesc': '同期待ち {count} 件',
  'home.rediagnose': '診断をやり直す',
  'home.refresh': '更新',
  'plan.title': '今日のプラン',
  'plan.subtitle': '診断結果と最近の行動データを組み合わせて今日の戦略を作ります。',
  'plan.missingTitle': '診断結果がありません',
  'plan.missingDesc': '個別プランを見るには先に診断を完了してください。',
  'plan.restartDiagnosis': '診断を再開',
  'plan.strategyVector': '戦略ベクトル',
  'plan.notes': '診断メモ',
  'plan.summary': 'プラン要約',
  'plan.explanation': '説明レシート',
  'plan.recovery': '回復プラン',
  'plan.evidence': '根拠',
  'plan.confidence': '軸ごとの信頼度',
  'plan.counterfactual': '反事実比較',
  'report.title': '週間レポート',
  'report.loading': 'レポートを生成中...',
  'report.empty': 'レポートを作るにはまだ学習データが足りません。',
  'report.analysis': '今週の分析',
  'report.delayedRecall': '7日遅延想起',
  'report.totalReviews': '総復習数',
  'report.newCards': '新規カード',
  'report.accuracy': '平均正答率',
  'report.streak': '連続学習',
  'report.confusions': 'よく混同する項目',
  'report.recovery': '回復指標',
  'web.loginSubtitle': 'Google でログインして、今日のキュー、レポート、実験、設定を確認します。',
  'web.nav.today': '今日',
  'web.nav.report': 'レポート',
  'web.nav.experiments': '実験',
  'web.nav.settings': '設定',
  'web.today.title': '今日のキュー',
  'web.today.empty': '今日処理するカードはありません。',
  'web.today.drills': 'ドリル',
  'web.today.plan': 'プラン説明',
  'web.report.title': '週間レポート',
  'web.experiments.title': '実験割り当て',
  'web.experiments.subtitle': '現在適用中の実験とその目的を確認できます。',
  'web.settings.title': '設定',
  'web.settings.subtitle': 'モバイルと Web に共通で適用される表示モードと言語を管理します。',
  'web.delete.redirect': '削除後、ログイン画面に移動します。',
};

const COPY = {
  ko: KO,
  en: EN,
  ja: JA,
} as const satisfies Record<SupportedLocale, UiCopyTable>;

export type { UiCopyKey };

export function getUiCopy(
  locale: SupportedLocale,
  key: UiCopyKey,
  params?: Record<string, string | number>,
): string {
  const template = COPY[locale][key] ?? COPY.ko[key] ?? key;
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, token: string) => String(params[token] ?? ''));
}
